server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index _shell.html;   # ไม่มีก็ได้ แต่อย่างน้อย try_files ต้องชี้ถูก

    location / {
        try_files $uri $uri/ /_shell.html;
    }

    location /health {
        return 200 'OK';
        add_header Content-Type text/plain;
    }
}
